#!/bin/bash


RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color



if [ "$1" == "" ]
then
	M="Fix"
else
	M=$1
fi


echo -e "${BLUE}GIT ADD .${NC}"
git add .

echo -e "${BLUE}GIT COMMIT -M ${M}${NC}"
git commit -m $M

echo -e "${BLUE}GIT PULL${NC}"
git pull

if [ $? != 1 ]
then 
	echo "No errors while pushing".
	echo -e "${BLUE}GIT PUSH${NC}"
	git push
	echo -e "${BLUE}big G be done here #orderrestored${NC}"
	#say "BIG G    IS DONE HERE"
	#echo " $(date) Big G saved you this time as well." > ~/logs/bigGsaves.txt
fi

